name: DeepSource Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: update npm
        run: npm install -g npm

      - name: Install dependencies
        run: npm install
        
      - name: Run DeepSource analysis
        run: npx deepsource analyze
        env:
          DEEPSOURCE_API_KEY: ${{ secrets.DEEPSOURCE_API_KEY }}
